trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

stages:
  - stage: build
    displayName: Build Application
    jobs:
      - job: 
        displayName: Build Job
        steps:
          - task: UseDotNet@2
            displayName: Use .NET6 to build
            inputs:
              version: "6.0.x"
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Restore NuGet packages
            inputs:
              command: 'restore'
              projects: '$(solution)'

          - task: DotNetCoreCLI@2
            displayName: Build .NET application
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release'

          - task: DotNetCoreCLI@2
            displayName: Publish .NET application
            inputs:
              command: 'publish'
              projects: '$(solution)'
              publishWebProjects: True
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

          - task: ArchiveFiles@2
            displayName: Create ZIP Artifact
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/WebApp.zip'
              replaceExistingArchive: true