trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

stages:

  - stage:
    displayName: build application
    jobs:
      - job:
        displayName: build job
        steps:
          - task: UseDotNet@2
            displayName: Use .NET6 to build
            inputs:
              version: "6.0.x"
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Build .NET application
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release'

  - stage:
    displayName: run unit test
    jobs:
      - job:
        displayName: unit test job
        steps:
          - task: DotNetCoreCLI@2
            displayName: run tests
            inputs:
              command: test
              projects: '$(solution)'
              arguments: '--configuration Release'

  - stage:
    displayName: deploy application
    condition: succeeded('run unit test')
    jobs:
      - deployment: deployJob
        displayName: Deploy to Azure App Service
        environment: 'dep'  # Replace with your Azure App Service environment name
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Azure for Students(49f57a7e-fb32-4222-8760-e1ec1a6765db)'
                  appType: 'webApp'
                  WebAppName: 'WebApp1997'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'


        

    
    




