trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

stages:
  - stage: build
    displayName: Build Application
    jobs:
      - job: 
        displayName: Build Job
        steps:
          - task: UseDotNet@2
            displayName: Use .NET6 to build
            inputs:
              version: "6.0.x"
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Build .NET application
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release'

      - job: 
        displayName: Publish Build Artifacts
        steps:
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(build.ArtifactStagingDirectory)'
              artifact: 'drop'
              publishLocation: 'pipeline'

  - stage: test
    displayName: Run Unit Tests
    dependsOn: 
      - build
     
    jobs:
      - job: 
        displayName: Unit Test Job
        steps:
          - task: DotNetCoreCLI@2
            displayName: Run Tests
            inputs:
              command: test
              projects: '$(solution)'
              publishTestResults: true
              arguments: '--configuration Release'





