trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

stages:
  - stage:
    displayName: build application
    jobs:
      - job:
        displayName: build job
        steps:
          - task: UseDotNet@2
            displayName: Use .NET6 to build
            inputs:
              version: "6.0.x"
              includePreviewVersions: true
          - task: DotNetCoreCLI@2
            displayName: Build .NET application
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release'



        

    
    




