trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'

stages:
  - stage: build
    displayName: Build Application
    jobs:
      - job: 
        displayName: Build Job
        steps:
          - task: UseDotNet@2
            displayName: Use .NET6 to build
            inputs:
              version: "6.0.x"
              includePreviewVersions: true

          - task: DotNetCoreCLI@2
            displayName: Build .NET application
            inputs:
              command: 'build'
              projects: '$(solution)'
              arguments: '--configuration Release'

          - task: DotNetCoreCLI@2
            displayName: Build Package
            inputs:
              command: 'pack'
              projects: '$(solution)'
              arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifact: 'drop'
              publishLocation: 'pipeline'
  - stage: deploy
    displayName: deployment
    dependsOn:
      - buid
    jobs: 
      - job:
        displayName: trying to deploy
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure for Students(49f57a7e-fb32-4222-8760-e1ec1a6765db)'
              appType: 'webApp'
              WebAppName: 'WebApp1997'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

      
  - stage: test
    displayName: Run Unit Tests
    dependsOn: 
      - build
     
    jobs:
      - job: 
        displayName: Unit Test Job
        steps:
          - task: DotNetCoreCLI@2
            displayName: Run Tests
            inputs:
              command: test
              projects: '$(solution)'
              publishTestResults: true
              arguments: '--configuration Release'


